name: CI

on:
  push:
    branches: [main]
    tags-ignore: ['**']
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint & Build
    runs-on: ubuntu-latest

    env:
      EXPENSLER_SHEETS_SCRIPT_ID: ${{ secrets.EXPENSLER_SHEETS_SCRIPT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: bash run.sh run::lint

      - name: Build
        run: bash run.sh run::build
