name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*'

jobs:
  release:
    name: Build & Deploy
    runs-on: ubuntu-latest

    env:
      EXPENSLER_TAG_VERSION: ${{ github.ref_name }}
      EXPENSLER_SHEETS_SCRIPT_ID: ${{ secrets.EXPENSLER_SHEETS_SCRIPT_ID }}
      clasp_config_auth: .clasprc.json
      clasp_config_project: ./output/.clasp.json

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: bash run.sh run::lint

      - name: Authenticate clasp
        run: echo '${{ secrets.CLASPRC_JSON }}' > .clasprc.json

      - name: Deploy to Google Apps Script
        run: bash run.sh run::deploy
